start_pose: [0, 0, 0]
camera_fov: 90
camera_range: 6
map_resolution: 0.05
map_width: 4000
map_height: 4000
map_origin: [-100, -100]

tasp_cell_size: 0.7
inflation_radius_m: 0.6
astar_connectivity: 8
wp_min_spacing: 0.7
inflated_tasp_cell: 1.8
tasp_goal_tolerance: 1.3
wait_duration: 10.0
rate_hz: 2

remove_btp_threshold_distance: 0.1
sampling_resolution: 0.1

# for offline boustrophedon planner
use_turn_trim: true
turn_margin_cells: 1
densify_step: 0.25
enable_smoothing: false
smoothing_iterations: 1
corner_lookahead_pts: 2

circular_region_radius: 5.5
duplicate_threshold: 2
sliding_window: 90
batch: 60